#FROM node:18-alpine
FROM mcr.microsoft.com/devcontainers/javascript-node:18

WORKDIR /app
COPY ./nextjs ./
#WORKDIR /app/nextjs
RUN npm install

#CMD [ "npm" , "run" , "dev"]

CMD ["sleep","infinity"]