services:
  nextjs:
    build: 
      context:  ../
      dockerfile: ./.docker/nextjs/Dockerfile

    ports:
      - 3000:3000
    #volumes:
    #  - ../nextjs:/app
      #- /app/node_modules
      #- /app/.next
      